// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Lakebase DB: must be a postgresql:// URL (not prisma+postgres://). See https://pris.ly/d/config-url
function getDatasourceUrl(): string {
  const url =
    process.env["LAKEBASE_DATABASE_URL"] ?? process.env["DATABASE_URL"];
  if (url == null || typeof url !== "string") {
    throw new Error(
      "LAKEBASE_DATABASE_URL or DATABASE_URL must be set (Prisma datasource)."
    );
  }
  const s = url.trim();
  if (!s) {
    throw new Error(
      "LAKEBASE_DATABASE_URL or DATABASE_URL is empty. Set a valid PostgreSQL URL."
    );
  }
  if (!s.startsWith("postgresql://") && !s.startsWith("postgres://")) {
    throw new Error(
      `Database URL must use scheme postgresql:// or postgres://. ` +
        `Got: ${s.split("://")[0] || "(empty)"}. ` +
        "For Lakebase use a PostgreSQL connection string (postgresql://...)."
    );
  }
  // Lakebase requires sslmode=require (otherwise P1010 "denied access" / "(not available)")
  if (/@[^/]*\.databricks\.com/i.test(s) && !/sslmode=/i.test(s)) {
    const separator = s.includes("?") ? "&" : "?";
    return `${s}${separator}sslmode=require`;
  }
  return s;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: getDatasourceUrl(),
  },
});
